Unikka:
  LinkChecker:
    url: ''
    defaultProfile: 'Unikka\LinkChecker\Profile\CheckAllLinks'
    defaultReporter: 'Unikka\LinkChecker\Reporter\LogBrokenLinks'
    concurrency: 10
    ignoreRobots: true
    excludeStatusCodes: []
    clientOptions:
      cookies: true
      connectionTimeout: 10
      timeout: 10
      allowRedirects: false
      auth: []
    notifications:
      enabled: true
      service: 'Unikka\LinkChecker\Service\EmailService'
      subject: 'Link checker results'
      minimumStatusCode: 400
      mail:
        sender:
          default:
            name: 'Unikka'
            address: 'test@example.com'
        recipient:
          default:
            name: 'Unikka'
            address: 'test@example.com'
        template:
          package: 'Unikka.LinkChecker'
          file: 'NotificationMail'
        attachment:
          enableMailAttachment: true
          csvHeader:
            - 'Status code'
            - 'URL'
            - 'Origin URL'
        logging:
          errors: log
          success: log


Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Unikka.LinkChecker': ['Modules']
    modules:
      management:
        submodules:
          linkchecker:
            label: 'Link Checker Module'
            controller: 'Unikka\LinkChecker\Controller\BackendController'
            description: 'Backend Modules for listing crawling states for URLs and images'
            icon: 'fas fa-link'
            privilegeTarget: 'Unikka.LinkChecker:Backend.Module.Management.LinkChecker'
