Noerdisch:
  LinkChecker:
    url: ''
    defaultProfile: 'Noerdisch\LinkChecker\Profile\CheckAllLinks'
    defaultReporter: 'Noerdisch\LinkChecker\Reporter\LogBrokenLinks'
    concurrency: 10
    ignoreRobots: true
    excludeStatusCodes: []
    clientOptions:
      cookies: true
      connectionTimeout: 10
      timeout: 10
      allowRedirects: false
      auth: []
    notifications:
      enabled: true
      service: 'Noerdisch\LinkChecker\Service\EmailService'
      subject: 'Link checker results'
      minimumStatusCode: 400
      mail:
        sender:
          default:
            name: 'Noerdisch'
            address: 'test@example.com'
        recipient:
          default:
            name: 'Noerdisch'
            address: 'test@example.com'
        template:
          package: 'Noerdisch.LinkChecker'
          file: 'NotificationMail'
        logging:
          errors: log
          success: log


Neos:
  Neos:
    modules:
      management:
        submodules:
          linkchecker:
            label: 'Link Checker Module'
            controller: 'Noerdisch\LinkChecker\Controller\BackendController'
            description: 'Backend Modules for listing crawling states for URLs and images'
            icon: 'fas fa-link'
            privilegeTarget: 'Noerdisch.LinkChecker:Backend.Module.Management.LinkChecker'
