Noerdisch:
  LinkChecker:
    url: ''
    defaultProfile: 'Noerdisch\LinkChecker\Profile\CheckAllLinks'
    defaultReporter: 'Noerdisch\LinkChecker\Reporter\LogBrokenLinks'
    concurrency: 10
    ignoreRobots: true
    exclude_status_codes: []
    clientOptions:
      cookies: true
      connectionTimeout: 10
      timeout: 10
      allowRedirects: false


Neos:
  Flow:
    security:
      authentication:
        providers:
          Neos.Neos:Backend:
            requestPatterns:
              'Noerdisch.LinkChecker:linkcheckerControllers':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Noerdisch\LinkChecker\Controller\.*'
  Neos:
    modules:
      management:
        submodules:
          linkchecker:
            label: 'Link Checker Module'
            controller: \Noerdisch\LinkChecker\Controller\BackendController
            description: 'Backend Modules for listing crawling states for URLs and images'
            icon: icon-link
            privilegeTarget: 'Noerdisch.LinkChecker:Backend'
